README.md
Problem
-------
The Rails stack in the README uses ActiveRecord and other internal pieces of Rails to describe the stack, which to me is missleading, especially compared to the other stacks in the REAME
Solution
--------
I've removed some of the internal Rails pieces and brought the stack more inline with what I believe to be similar to the other stacks.  Let me know if this isn't correct.
=> Adjust Rails stack

README.md
[X] I read the [Contribution Guide](CONTRIBUTING.md)
=> Adding more tools to some existing stacks.

README.md
[X] I read the [Contribution Guide](CONTRIBUTING.md)
[X] I followed the [do's and don'ts](CONTRIBUTING.md#contributing-dos-and-donts)
[X] This stack does not already exist
=> Rails Monitoring Stack

src/components/banner.js
[x] I read the [Contribution Guide](CONTRIBUTING.md)
=> Added PH link to banner.js

README.md
[ ] I read the [Contribution Guide](CONTRIBUTING.md)
=> using vue with electron

README.md
[x] I read the [Contribution Guide](CONTRIBUTING.md)
=> Fix link to CRA repository

README.md
[ ] I read the [Contribution Guide](CONTRIBUTING.md)
=> Added Game dev with Unity stack

README.md
[x] I read the [Contribution Guide](CONTRIBUTING.md)
[x] I followed the [do's and don'ts](CONTRIBUTING.md#contributing-dos-and-donts)
[x] This stack does not already exist
=> Add Contenful on Progressive Web App w/ Gatsby

README.md
[x] I read the [Contribution Guide](CONTRIBUTING.md)
[x] I followed the [do's and don'ts](CONTRIBUTING.md#contributing-dos-and-donts)
[x] This stack does not already exist
=> Add Strapi Fullstack with Gatsby deploy to Heroku

README.md
[ x] I read the [Contribution Guide](CONTRIBUTING.md)
=> Added shield to blog post

README.md
[ ] I read the [Contribution Guide](CONTRIBUTING.md)
=> Stack workflow automation

CONTRIBUTING.md
Late to the party, thinking about contributing, and I noticed a couple characters out of place.
=> H2 for H3, then for than

README.md
=> Some self-hosted goodness: GitLab, Zulip, Sentry, etc

README.md
=> Streaming stack - Kafka, Spark, Cassandra

README.md
=> User Behavior Analytics stack

README.md
List of people who use this template: https://github.com/wemake-services/wemake-django-template/wiki/Who-is-using-this-template
=> Adds wemake-django-template

README.md
Source code: https://github.com/wemake-services/wemake-vue-template/tree/master/template
Demo link: https://wemake-vue-demo.herokuapp.com/
=> Adds wemake-vue-template

README.md
=> Add code coverage and CI stack

README.md
- [  √ ] I read the [Contribution Guide](CONTRIBUTING.md)
- [ √  ] I followed the [do's and don'ts](CONTRIBUTING.md#contributing-dos-and-donts)
- [ √  ] This stack does not already exist
=> Add Laravel+Vue Stack

README.md
=> Docs: Removed duplicate text

README.md
=> Fixing typo on vuex url

CONTRIBUTING.md
=> fix code of conduct link

README.md
@dzello this is for #46 
Working on part 2 now (Awesome Linter results)
=> Awesome List Clean up part 1

README.md
=> Awesome List Clean up part 2

README.md
=> Fixed linting errors

README.md
=> feat(backend): new stack with java and spring boot

README.md
=> Fixed trivial w/ issues Java and Spring Boot stack

README.md
=> Fixed Spring Boot url

README.md
:rocket: A basis for reducing the configuration of your projects with nextJS, best development practices and popular libraries in the developer community.
=> add: New Front-end boilerplate with next.js

README.md
- [x ] I read the [Contribution Guide](CONTRIBUTING.md)
=> Added Udemy course for React Native + Hasura

README.md
=> Added FReMP Stack

README.md
=> Add Nextjs Blog Starter

README.md
=> Fixing link to GraphCMS starter blog

README.md
=> add mern stack

README.md
=> add db3 network
